### PR TITLE
Flush the IO writer after each log message

### PR DESCRIPTION
**Pull request by njam**
See #13

<details>
<summary>Example for acceptance testing</summary>

```rust
#[macro_use]
extern crate slog;
extern crate slog_json;

use std::sync::Mutex;
use slog::Drain;
use std::io;

struct MyWriter {}

impl io::Write for MyWriter {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        println!("Write: {}", String::from_utf8_lossy(buf));
        Ok(buf.len())
    }
    fn flush(&mut self) -> io::Result<()> {
        println!("Flush!");
        Ok(())
    }
}

fn main() {
    let writer = MyWriter {};
    let drain = slog_json::Json::new(writer)
        .set_flush(true)
        .build();
    let logger = slog::Logger::root(Mutex::new(drain).map(slog::Fuse), o!());

    for i in 1..3 {
        info!(logger, "Hello {}", i; "foo" => "12");
    }
}
```
</details>

### CODE REVIEW

**Comment by dpc** [comment]
I am not sure if doing the `flush` is always a good idea. It might slow down other people who did not use buffered writer... . Should it be an option?

**Comment by njam** [comment]
Makes sense. Should I turn it off by default (no flush)?

**Comment by dpc** [comment]
Yes, let's keep it the way it worked before. Otherwise, it would be somewhat of a breaking change.

**Comment by njam** [comment]
I agree. I've pushed a new version. Please review.

**Comment by dpc** [comment]
Welcome to the team. Please accept the invites, and release at your convenience.

**Comment by njam** [comment]
Cool, thanks!

**Pull request merged**
